media:
  input: public/assets
  output: /assets
  categories: ["image"]
content:
  - name: products
    label: Products
    type: collection
    path: _products
    view:
      fields: [coverImage, title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }

  # Home Page Configuration
  - name: home
    label: Home Page
    type: file
    path: _home
    file: _home/home.md
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: heroImage, label: Hero Image, type: image }
      - {
          name: sections,
          label: Sections,
          type: list,
          fields:
            [
              { name: heading, label: Heading, type: string, required: true },
              { name: content, label: Content, type: rich-text },
            ],
        }

  # About Us Page Configuration
  - name: about
    label: About Us Page
    type: file
    path: _about
    file: _about/about.md
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: content, label: Content, type: rich-text }

  # Header Configuration (shared across pages)
  - name: header
    label: Header
    type: file
    path: _common
    file: _common/header.md
    fields:
      - { name: logo, label: Logo, type: image }
      - {
          name: menu,
          label: Menu,
          type: list,
          fields:
            [
              { name: linkText, label: Link Text, type: string },
              { name: url, label: URL, type: string },
            ],
        }

  # Footer Configuration (shared across pages)
  - name: footer
    label: Footer
    type: file
    path: _common
    file: _common/footer.md
    fields:
      - { name: logo, label: Logo, type: image }
      - {
          name: links,
          label: Links,
          type: list,
          fields:
            [
              { name: linkText, label: Link Text, type: string },
              { name: url, label: URL, type: string },
            ],
        }
