media:
  input: public/assets
  output: /assets
  categories: ["image", "document"]
content:
  - name: products
    label: Products
    type: collection
    path: public/_products
    view:
      fields: [coverImage, title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }

  # Home Page Configuration
  - name: home
    label: Home Page
    type: file
    path: src/assets/_home/home.md
    fields:
      - { name: heading, label: Heading, type: string, required: true }
      - { name: buttonText, label: Button Text, type: string, required: true }
      - { name: buttonLink, label: Button Link, type: string, required: true }
      - { name: heroImage, label: Hero Image, type: image }
      - {
          name: sections,
          label: Sections,
          type: object,
          fields:
            [
              {
                name: misson,
                label: Mission Section,
                type: object,
                required: true,
                fields:
                  [
                    {
                      name: missionTopHeading,
                      label: Top Heading,
                      type: string,
                    },
                    { name: missionHeading, label: Heading, type: string },
                    {
                      name: mission-content,
                      label: Mission Details,
                      type: object,
                      fields:
                        [
                          {
                            name: missionContentHeading,
                            label: Mission Content Heading,
                            type: string,
                          },
                          {
                            name: missionContent,
                            label: Mission Content,
                            type: rich-text,
                          },
                          {
                            name: buttonText,
                            label: Button Text,
                            type: string,
                            required: true,
                          },
                          {
                            name: buttonLink,
                            label: Button Link,
                            type: string,
                            required: true,
                          },
                          {
                            name: missionImage1,
                            label: First Image,
                            type: image,
                          },
                          {
                            name: missionImage2,
                            label: Second Image,
                            type: image,
                          },
                        ],
                    },
                  ],
              },
              {
                name: innovation,
                label: Innovation Section,
                type: object,
                required: true,
                fields:
                  [
                    {
                      name: innovationHeading,
                      label: Innovation Heading,
                      type: string,
                    },
                  ],
              },
            ],
        }

  # About Us Page Configuration
  - name: about
    label: About Us Page
    type: file
    path: src/assets/_about/about.md
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: content, label: Content, type: rich-text }

  # Header Configuration (shared across pages)
  - name: header
    label: Header
    type: file
    path: src/assets/_common/header.md
    fields:
      - { name: logo, label: Logo, type: image }
      - {
          name: menu,
          label: Menu,
          type: object,
          fields:
            [
              { name: linkText, label: Link Text, type: string },
              { name: url, label: URL, type: string },
            ],
        }

  # Footer Configuration (shared across pages)
  - name: footer
    label: Footer
    type: file
    path: src/assets/_common/footer.md
    fields:
      - { name: logo, label: Logo, type: image }
      - {
          name: links,
          label: Links,
          type: object,
          fields:
            [
              { name: linkText, label: Link Text, type: string },
              { name: url, label: URL, type: string },
            ],
        }
    # Demo Section (shared across pages)
  - name: demo
    label: Demo
    type: file
    path: src/assets/_common/demo.md
    fields:
      - { name: demoHeading, label: Demo Heading, type: string }
      - { name: firstVideo, label: First Video (URL), type: string }
      - { name: secondVideo, label: Second Video (URL), type: string }

    # Contact Section (shared across pages)
  - name: contact
    label: Contact
    type: file
    path: src/assets/_common/contact.md
    fields:
      - { name: contactHeading, label: Contact Heading, type: string }
      - { name: backgroundText, label: backgroundText, type: string }
      - { name: buttonText, label: Button Text, type: string }
      - { name: buttonLink, label: Button Link, type: string }

# Fonts (shared across pages)
  - name: fonts
    label: Fonts
    type: file
    path: src/assets/_common/font.json
    fields:
    - name: defaultFontName
      label: Default Font Name
      type: string
      required: true
    - name: defaultFontFileName
      label: Default Font File Name ( with extention e.g. inter-regular.tff )
      type: string
      required: true
    - name: specificFontName
      label: Specific Font Name
      type: string
      required: true
    - name: SpecificFontFileName
      label: Specific Font File Name ( with extention e.g. inter-regular.tff )
      type: string
      required: true


